### PR TITLE
Add README.ja.md

### PR DESCRIPTION
**Pull request by nikukyugamer**
Dear gav- and nickorr

Your product **RESTfm** is too great and awesome so I'm impressed deeply.
I'd love many FMS users to use this wonderful product.

Therefore I translate README.md into Japanese, my native language.
I'm convinced that this document helps Japanese users to know **RESTfm**.

----------------------------------------

Now I'm also translating manual, API document and other description pages.
If possible, I'd like you to pull them.

Sincerely

### CODE REVIEW

**Comment by gav-** [comment]
Hi corselia,

Thank you for your marvellous contribution.

Unfortunately the README.md was rather out of date, and your pull request prompted me to give it an update.

If you would consider incorporating these changes, then it would be a great pleasure to include your Japanese version.

Regards,

gav-

**Comment by nikukyugamer** [comment]
Dear gav-

Thank you for your favorable reply!
I modified README.ja.md right away.

I wish this document enables many Japanese to use your marvelous product.

**Comment by gav-** [comment]
Hi corselia,

I have just one query before I merge this (and I must apologise that I had to resort to using Google Translate).

The original text:
> Product support is available via paid sponsorship

Your translation:
> 開発への支援を頂いた方にはサポートを提供しております

Google's translation back to English (again I apologise for this, but I think it is important):
> We are providing support for those who received support for development

It needs to be understood (by the reader) that product support is not free, and is only provided to those that have sponsored (i.e. paid money for) RESTfm development.

Could you please let me know if your translation covers this meaning adequately ?

Regards,

gav.

**Comment by nikukyugamer** [comment]
@gav- 
hi gav-, also in this case, sorry for late^n response 😓 

## '開発への支援を頂いた方にはサポートを提供しております'
btw `開発への支援を頂いた方にはサポートを提供しております` means below each part.

- `開発への支援を頂いた方` means `people who have sponsored for RESTfm development`
- `サポートを提供しております` means `We are providing support`
- `には` means `for`
- sorry not included `(i.e. paid money for)`. it means `（例えば支援金のお支払）` in Japanese

## merged sentences
as a result, merged abobe sentences is below.

- Japanese
>  開発への支援（例えば支援金のお支払）を頂いた方にはサポートを提供しております

- English
> Product support is available via paid sponsorship

## how is it?
how is this translation?
if be problem(s), I modify, so please tell me it.

sincerely, awesome product `RESTfm`!

**Comment by gav-** [comment]
Closing this pull request, not possible to maintain internally,

**Pull request closed without merging**
